services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    volumes:
      - redisinsight:/data
    ports:
      - "5540:5540"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-kuizz
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17 # Use a specific version for stability
    container_name: postgres-kuizz
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_kuizz:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:9
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  redisinsight:
  postgres_data_kuizz:
