services:
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    volumes:
      - redisinsight:/data
    ports:
      - "5540:5540"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: kuizz-redis
    ports:
      - "6379:6379"

volumes:
  redisinsight:
