server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # membaca docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          service: kuizz
          __path__: /var/lib/docker/containers/*/*.log

  # membaca log file dev
  - job_name: kuizz-dev
    static_configs:
      - targets:
          - localhost
        labels:
          job: kuizz-dev
          service: kuizz
          __path__: /logs/*.log
